// LOGIN ACTIONS //
export const REQUEST_LOGIN = "REQUEST_LOGIN"
export const SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN"
export const FAILED_LOGIN = "FAILED_LOGIN"
export const LOG_OUT = "LOG_OUT"

// USER ACTIONS //
export const USER_REQUEST = "USER_REQUEST"
export const USER_SUCCESS = "USER_SUCCESS"
export const USER_FAILURE = "USER_FAILURE"
export const CREATE_USER = "CREATE_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER"