export const REQUESTING = "REQUESTING"


// LOGIN ACTIONS //
export const SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN"
export const FAILED_LOGIN = "FAILED_LOGIN"
export const LOG_OUT = "LOG_OUT"

// USER ACTIONS //
export const USER_REQUEST = "USER_REQUEST"
export const USER_SUCCESS = "USER_SUCCESS"
export const USER_FAILURE = "USER_FAILURE"
export const CREATE_USER = "CREATE_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER"

// POST ACTIONS 
export const REQUEST_POST = 'REQUEST_POST'
export const POST_SUCCESS = 'POST_SUCCESS'
export const POST_FAILURE = 'POST_FAILURE'
export const CREATE_POST = 'CREATE_POST'
export const EDIT_POST_CAPTION = 'EDIT_POST_CAPTION'
export const DELETE_POST = 'DELETE_POST'
export const ADD_LIKE = 'ADD_LIKE'

// POST COMMENTS ACTIONS //
export const SUBMITTED_COMMENT = 'SUBMITTED_COMMENT'
export const ADD_COMMENT = 'ADD_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

// END OF POST ACTIONS





// FOLLOWS ACTIONS //


